# https://neo4j.com/docs/operations-manual/current/docker/docker-compose-standalone/
services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/red_pill
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
